---
- name: Send notify to Telegram
  hosts: localhost
  tasks:
    - name: Notify via Telegram
      community.general.telegram:
        token: '7281232336:AAEOPDNXGU2iwOwyo3C8yVFV4a5tAdvNGIQ'
        api_method: sendMessage
        api_args:
          chat_id: 7397749412  # Replace with your actual chat ID
          text: "Security Alert: 172.16.188.14 is suspected of a brute force attack. Immediate action has been taken to isolate/block the IP on End devices firewalls, Fortigate firewall, Network devices (ACLs), and on Servers."
          parse_mode: markdown
          disable_web_page_preview: true
          disable_notification: true
