---
- name: Block specified IP on Windows Firewall
  hosts: Victim
  gather_facts: no
  collections:
    - community.windows
  vars:
    attacker_ip: "{{ attacker_ip }}"
  tasks:
    - name: Block inbound traffic from attacker_ip
      community.windows.win_firewall_rule:
        name: "Block {{ attacker_ip }}"
        direction: in
        action: block
        remoteip: "{{ attacker_ip }}"
        protocol: any
        enabled: yes
        state: present

    - name: Display result of firewall rule creation
      debug:
        msg: "Firewall rule to block {{ attacker_ip }} created."