---
- name: Undo Brute Force remediation
  hosts: fortigate
  gather_facts: no
  collections:
    - fortinet.fortios
  connection: httpapi
  vars:
    vdom: "root"
    ansible_httpapi_use_ssl: no
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 80
  tasks:

    - name: Delete Block traffic from port1 to port2 policy
      fortios_firewall_policy:
        vdom: "{{ vdom }}"
        state: "absent"
        firewall_policy:
          policyid: 51

    - name: Delete Block traffic from port1 to port4 policy
      fortios_firewall_policy:
        vdom: "{{ vdom }}"
        state: "absent"
        firewall_policy:
          policyid: 52

    - name: Delete Block traffic from port1 to port5 policy
      fortios_firewall_policy:
        vdom: "{{ vdom }}"
        state: "absent"
        firewall_policy:
          policyid: 53

    - name: Remove the malicious IP address definition
      fortios_firewall_address:
        vdom: "{{ vdom }}"
        state: "absent"
        firewall_address:
          name: "Malicious_IP"

- name: Undo ACL configuration to VLAN 220 on Cisco Device
  hosts: cisco
  gather_facts: no
  vars:
    attacker_ip: "{{ attacker_ip }}"
  tasks:
    - name: Remove ACL configuration
      cisco.ios.ios_config:
        lines:
          - no access-list 110
        parents: []

    - name: Remove ACL from VLAN 220 interface
      cisco.ios.ios_config:
        lines:
          - no ip access-group 110 in
        parents: "interface Vlan220"

    - name: Verify ACL has been removed from VLAN 220 interface
      cisco.ios.ios_command:
        commands:
          - show running-config interface Vlan220
      register: vlan_config

    - name: Show verification results
      debug:
        msg: "{{ vlan_config.stdout_lines }}"