---
- name: Brute Force remediation
  hosts: Victim_PC
  gather_facts: no
  vars:
    attacker_ip: "{{ attacker_ip }}"
  tasks:
    - name: Display security alert for brute force attack
      community.windows.win_msg:
        display_seconds: 30
        msg: "Security Alert: {{ attacker_ip }} is suspected of a brute force attack. Immediate action will be taken."

- hosts: localhost
  gather_facts: no
  tasks:
    - name: Send Telegram notification
      community.general.telegram:
        token: '7281232336:AAEOPDNXGU2iwOwyo3C8yVFV4a5tAdvNGIQ'
        api_method: sendMessage
        api_args:
          chat_id: 7397749412
          text: "Security Alert: {{ attacker_ip }} is suspected of a brute force attack. Immediate action has been taken to isolate/block the IP on End devices firewalls, Fortigate firewall, Network devices (ACLs), and on Servers."
          parse_mode: markdown
          disable_web_page_preview: true
          disable_notification: true

- hosts: fortigate
  gather_facts: no
  collections:
    - fortinet.fortios
  connection: httpapi
  vars:
    vdom: "root"
    ansible_httpapi_use_ssl: no
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 80
  tasks:
    - name: Define the malicious IP address
      fortios_firewall_address:
        vdom: "{{ vdom }}"
        state: "present"
        firewall_address:
          name: "Attacker_IP"
          subnet: "{{ attacker_ip }} 255.255.255.255"

    - name: Block traffic from port1 to port2
      fortios_firewall_policy:
        vdom: "{{ vdom }}"
        state: "present"
        firewall_policy:
          policyid: 51
          name: "Block_port1_to_port2"
          srcintf: [{"name": "port1"}]
          dstintf: [{"name": "port2"}]
          srcaddr: [{"name": "Attacker_IP"}]
          dstaddr: [{"name": "all"}]
          action: "deny"
          schedule: "always"
          service: [{"name": "ALL"}]
          logtraffic: "all"

    - name: Block traffic from port1 to port4
      fortios_firewall_policy:
        vdom: "{{ vdom }}"
        state: "present"
        firewall_policy:
          policyid: 52
          name: "Block_port1_to_port4"
          srcintf: [{"name": "port1"}]
          dstintf: [{"name": "port4"}]
          srcaddr: [{"name": "Attacker_IP"}]
          dstaddr: [{"name": "all"}]
          action: "deny"
          schedule: "always"
          service: [{"name": "ALL"}]
          logtraffic: "all"

    - name: Block traffic from port1 to port5
      fortios_firewall_policy:
        vdom: "{{ vdom }}"
        state: "present"
        firewall_policy:
          policyid: 53
          name: "Block_port1_to_port5"
          srcintf: [{"name": "port1"}]
          dstintf: [{"name": "port5"}]
          srcaddr: [{"name": "Attacker_IP"}]
          dstaddr: [{"name": "all"}]
          action: "deny"
          schedule: "always"
          service: [{"name": "ALL"}]
          logtraffic: "all"
          
    - name: Move policy 51 before policy 60
      fortinet.fortios.fortios_firewall_policy:
        vdom: "{{ vdom }}"
        state: "present"
        action: "move"
        self: 51
        before: 60
    - name: Move policy 52 before policy 60
      fortinet.fortios.fortios_firewall_policy:
        vdom: "{{ vdom }}"
        state: "present"
        action: "move"
        self: 52
        before: 60
    - name: Move policy 53 before policy 60
      fortinet.fortios.fortios_firewall_policy:
        vdom: "{{ vdom }}"
        state: "present"
        action: "move"
        self: 53
        before: 60

- name: Configure ACL to allow only HTTP and HTTPS from attacker_ip and apply to VLAN 220
  hosts: cisco
  gather_facts: no
  vars:
    attacker_ip: "{{ attacker_ip }}"
  tasks:
    - name: Retrieve current ACL configuration
      cisco.ios.ios_command:
        commands:
          - show running-config | include access-list
      register: acl_output

    - name: Debug ACL output
      debug:
        var: acl_output.stdout_lines

    - name: Manually configure ACLs
      cisco.ios.ios_config:
        lines:
          - no access-list 110
          - access-list 110 permit tcp {{ attacker_ip }} 0.0.0.0 any eq 80
          - access-list 110 permit tcp {{ attacker_ip }} 0.0.0.0 any eq 443
          - access-list 110 deny ip {{ attacker_ip }} 0.0.0.0 any
          - access-list 110 permit ip any any
        parents: []

    - name: Apply ACL to VLAN 220 interface
      cisco.ios.ios_config:
        lines:
          - ip access-group 110 in
        parents: "interface Vlan220"

    - name: Verify ACL is applied to VLAN 220 interface
      cisco.ios.ios_command:
        commands:
          - show running-config interface Vlan220
      register: vlan_config

    - name: Show verification results
      debug:
        msg: "{{ vlan_config.stdout_lines }}"

- name: Create inbound firewall rule to block attacker_ip on Windows
  hosts: Victim_PC
  gather_facts: no
  collections:
    - community.windows
  vars:
    attacker_ip: "{{ attacker_ip }}"
  tasks:
    - name: Block inbound traffic from attacker_ip
      community.windows.win_firewall_rule:
        name: "Block Attacker IP"
        direction: in
        action: block
        remoteip: "{{ attacker_ip }}"
        protocol: any
        enabled: yes
        state: present

    - name: Display result of firewall rule creation
      debug:
        msg: "Firewall rule to block {{ attacker_ip }} created."