---
- name: Undo Brute Force remediation on Fortigate
  hosts: fortigate
  gather_facts: no
  collections:
    - fortinet.fortios
  connection: httpapi
  vars:
    vdom: "root"
  tasks:
    - name: Delete Block traffic from port1 to port2 policy
      fortios_firewall_policy:
        vdom: "{{ vdom }}"
        state: "absent"
        firewall_policy:
          policyid: 51

    - name: Delete Block traffic from port1 to port4 policy
      fortios_firewall_policy:
        vdom: "{{ vdom }}"
        state: "absent"
        firewall_policy:
          policyid: 52

    - name: Delete Block traffic from port1 to port5 policy
      fortios_firewall_policy:
        vdom: "{{ vdom }}"
        state: "absent"
        firewall_policy:
          policyid: 53

    - name: Remove the malicious IP address definition
      fortios_firewall_address:
        vdom: "{{ vdom }}"
        state: "absent"
        firewall_address:
          name: "Attacker_IP"

- name: Undo ACL configuration on Cisco Device
  hosts: cisco
  gather_facts: no
  vars:
    attacker_ip: "{{ attacker_ip }}"
  tasks:
    - name: Remove ACL configuration
      cisco.ios.ios_config:
        lines:
          - no access-list 110
        parents: []

    - name: Remove ACL from VLAN 220 interface
      cisco.ios.ios_config:
        lines:
          - no ip access-group 110 in
        parents: "interface Vlan220"

- name: Remove inbound firewall rule on Windows to unblock attacker_ip
  hosts: Victim_PC
  gather_facts: no
  collections:
    - community.windows
  tasks:
    - name: Remove firewall rule to unblock attacker_ip
      community.windows.win_firewall_rule:
        name: "Block Attacker IP"
        state: absent
