---
- name: Configure Internal_Switch
  hosts: Internal_Switch
  gather_facts: no
  tasks:
    - name: send configuration commands to IOS
      ansible.netcommon.telnet:
        password: cisco
        prompts:
          - "Password: "
          - "[>#]"
        command:
          - terminal length 0
          - configure terminal
          - hostname ios01

    - name: run show commands
      ansible.netcommon.telnet:
        password: cisco
        prompts:
          - "Password: "
          - "[>#]"
        command:
          - terminal length 0
          - show version
