---
- hosts: fortigate
  gather_facts: no
  collections:
    - fortinet.fortios
  connection: httpapi
  vars:
    vdom: "root"
    ansible_httpapi_use_ssl: no
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 80
  tasks:
    - name: Remove the firewall policy blocking traffic
      fortios_firewall_policy:
        vdom: "{{ vdom }}"
        state: "absent"
        firewall_policy:
          policyid: "{{ global_counter }}"

    - name: Remove the malicious IP address
      fortios_firewall_address:
        vdom: "{{ vdom }}"
        state: "absent"
        firewall_address:
          name: "Exfiltrator_IP"
