---
- name: DNS Amplification remediation
  hosts: Victim_PC
  gather_facts: no
  vars:
    victim_ip: "{{ victim_ip }}"
    attacker_ip: "{{ attacker_ip }}"
  tasks:
    - name: Display security alert for brute force attack
      community.windows.win_msg:
        display_seconds: 30
        msg: "Security Alert: {{ attacker_ip }} is suspected of a dns amplification attack. Immediate action required. Immediate action will be taken."

- hosts: localhost
  gather_facts: no
  tasks:
    - name: Send Telegram notification
      community.general.telegram:
        token: '7281232336:AAEOPDNXGU2iwOwyo3C8yVFV4a5tAdvNGIQ'
        api_method: sendMessage
        api_args:
          chat_id: 7397749412
          text: "Security Alert: {{ attacker_ip }} is suspected of a dns amplification attack. Immediate action has been taken to remediate the attack."
          parse_mode: markdown
          disable_web_page_preview: true
          disable_notification: true

- hosts: fortigate
  gather_facts: no
  collections:
    - fortinet.fortios
  connection: httpapi
  vars:
    vdom: "root"
    ansible_httpapi_use_ssl: no
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 80
  tasks:
    - name: Modify UDP_FLOOD DoS policy to block UDP flood attacks
      fortios_firewall_dos_policy:
        vdom: "{{ vdom }}"
        state: "present"
        firewall_dos_policy:
          policyid: 6
          name: "UDP_FLOOD"
          interface: "port1"
          srcaddr:
            - name: "any"
          dstaddr:
            - name: "INT_USERS address"
          service:
            - name: "ALL_UDP"
          status: "enable"
          anomaly:
            - name: "tcp_syn_flood"
              threshold: 2000
              action: "pass"
              log: "enable"
            - name: "tcp_port_scan"
              threshold: 1000
              action: "pass"
              log: "enable"
            - name: "tcp_src_session"
              threshold: 5000
              action: "pass"
              log: "enable"
            - name: "tcp_dst_session"
              threshold: 5000
              action: "pass"
              log: "enable"
            - name: "udp_flood"
              status: "enable"
              log: "enable"
              threshold: 2000
              action: "block"  # This line adds the block action for UDP flood
            - name: "udp_scan"
              threshold: 2000
              action: "pass"
              log: "enable"
            - name: "udp_src_session"
              threshold: 5000
              action: "pass"
              log: "enable"
            - name: "udp_dst_session"
              threshold: 5000
              action: "pass"
              log: "enable"
            - name: "icmp_flood"
              threshold: 250
              action: "pass"
              log: "enable"
            - name: "icmp_sweep"
              threshold: 100
              action: "pass"
              log: "enable"
            - name: "icmp_src_session"
              threshold: 300
              action: "pass"
              log: "enable"
            - name: "icmp_dst_session"
              threshold: 1000
              action: "pass"
              log: "enable"
            - name: "ip_src_session"
              threshold: 5000
              action: "pass"
              log: "enable"
            - name: "ip_dst_session"
              threshold: 5000
              action: "pass"
              log: "enable"
            - name: "sctp_flood"
              threshold: 2000
              action: "pass"
              log: "enable"
            - name: "sctp_scan"
              threshold: 1000
              action: "pass"
              log: "enable"
            - name: "sctp_src_session"
              threshold: 5000
              action: "pass"
              log: "enable"
            - name: "sctp_dst_session"
              threshold: 5000
              action: "pass"
              log: "enable"
