---
- name: Send dynamic security alert messages to PCs based on attack type
  hosts: Monitoring
  gather_facts: no
  vars:
    attacker_ip: "{{ attacker_ip }}"
    attack_type: "{{ attack_type }}"
  tasks:
    - name: Display security alert for brute force attack
      community.windows.win_msg:
        display_seconds: 5
        msg: "Security Alert: {{ attacker_ip }} is suspected of a brute force attack. Immediate action required."
      when: attack_type == "brute_force"

    - name: Display security alert for DNS amplification attack
      community.windows.win_msg:
        display_seconds: 5
        msg: "Security Alert: {{ attacker_ip }} is suspected of a DNS amplification attack. Immediate action required."
      when: attack_type == "dns_amplification"

    - name: Display security alert for DNS exfiltration attack
      community.windows.win_msg:
        display_seconds: 5
        msg: "Security Alert: {{ attacker_ip }} is suspected of DNS exfiltration. Immediate action required."
      when: attack_type == "dns_exfiltration"