---
- name: Undo Phishing remediation
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Send Telegram notification
      community.general.telegram:
        token: '7281232336:AAEOPDNXGU2iwOwyo3C8yVFV4a5tAdvNGIQ'
        api_method: sendMessage
        api_args:
          chat_id: 7397749412
          text: "You have chosen to undo the remediation for the phishing attack, have a good day!"
          parse_mode: markdown
          disable_web_page_preview: true
          disable_notification: true

- name: Undo FortiGate URL Filtering Configuration (Phishing)
  hosts: fortigate
  gather_facts: no
  collections:
    - fortinet.fortios
  connection: httpapi
  vars:
    vdom: "root"  # Adjust if needed
  tasks:
    - name: Remove URL Filter Entry
      fortios_webfilter_urlfilter:
        vdom: "{{ vdom }}"
        state: "absent"
        webfilter_urlfilter:
          name: "URL_Filter"  # Ensure this matches the name used in the configuration
          entries:
            - id: 1