---
- name: Phishing remediation
  hosts: windows
  gather_facts: no
  tasks:
    - name: Display security alert for Phishing attack
      community.windows.win_msg:
        display_seconds: 30
        msg: "Security Alert: Phishing attack detected. Immediate action will be taken."

- hosts: localhost
  gather_facts: no
  tasks:
    - name: Send Telegram notification
      community.general.telegram:
        token: '7281232336:AAEOPDNXGU2iwOwyo3C8yVFV4a5tAdvNGIQ'
        api_method: sendMessage
        api_args:
          chat_id: 7397749412
          text: "Security Alert: Phishing attack. Immediate action has been taken"
          parse_mode: markdown
          disable_web_page_preview: true
          disable_notification: true

- name: Configure FortiGate URL Filtering (Phishing)
  hosts: fortigate
  gather_facts: no
  collections:
    - fortinet.fortios
  connection: httpapi
  vars:
    vdom: "root"  # Adjust as necessary
    ansible_httpapi_use_ssl: no
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 80  # Adjust port as necessary
  tasks:
    - name: Configure URL Filter
      fortios_webfilter_urlfilter:
        vdom: "{{ vdom }}"
        state: "present"
        webfilter_urlfilter:
          name: "URL_Filter"
          entries:
            - id: 1
              action: "block"
              url: "*"  # Adjust URL as necessary, "*" blocks all
          status: "enable"