---
- name: Port Stealing remediation
  hosts: windows
  gather_facts: no
  vars:
    attacker_ip: "{{ attacker_ip }}"
  tasks:
    - name: Display security alert for Port Stealing attack
      community.windows.win_msg:
        display_seconds: 30
        msg: "Security Alert: Port Stealing attack detected from port:{{ attacker_ip }}. Immediate action will be taken."

- hosts: localhost
  gather_facts: no
  tasks:
    - name: Send Telegram notification
      community.general.telegram:
        token: '7281232336:AAEOPDNXGU2iwOwyo3C8yVFV4a5tAdvNGIQ'
        api_method: sendMessage
        api_args:
          chat_id: 7397749412
          text: "Security Alert: Port Stealing attack detected from port:{{ attacker_ip }}. Immediate action has been taken."
          parse_mode: markdown
          disable_web_page_preview: true
          disable_notification: true