---
- name: Undo SQL Injection remediation
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Send Telegram notification
      community.general.telegram:
        token: '7281232336:AAEOPDNXGU2iwOwyo3C8yVFV4a5tAdvNGIQ'
        api_method: sendMessage
        api_args:
          chat_id: 7397749412
          text: "Security Alert: {{ attacker_ip }} was previously suspected of a sql injection attack. You have chosen to unblock this IP address, have a good day!"
          parse_mode: markdown
          disable_web_page_preview: true
          disable_notification: true
          
- hosts: fortigate
  gather_facts: no
  collections:
    - fortinet.fortios
  connection: httpapi
  vars:
    vdom: "root"
    ansible_httpapi_use_ssl: no
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 80
  tasks:
    - name: Revert IPS sensor for SQL Injection Attack
      fortinet.fortios.fortios_ips_sensor:
        vdom: "{{ vdom }}"
        state: "present"
        ips_sensor:
          name: "SQL_INJECTION_ATTACK"
          entries:
            - id: "1"
              rule:
                - id: "15621"
              action: "pass"
              log_packet: "enable"
              status: "enable"
