---
- name: Undo TCP SYN Flood remediation
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Send Telegram notification
      community.general.telegram:
        token: '7281232336:AAEOPDNXGU2iwOwyo3C8yVFV4a5tAdvNGIQ'
        api_method: sendMessage
        api_args:
          chat_id: 7397749412
          text: "Security Alert: {{ attacker_ip }} was previously suspected of a tcp syn flood attack. You have chosen to unblock this IP address, have a good day!"
          parse_mode: markdown
          disable_web_page_preview: true
          disable_notification: true

- hosts: fortigate
  gather_facts: no
  collections:
    - fortinet.fortios
  connection: httpapi
  vars:
    vdom: "root"
    ansible_httpapi_use_ssl: no
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 80
  tasks:
    - name: Modify TCP_SYN_FLOOD DoS policy to monitor TCP SYN flood attacks
      fortios_firewall_dos_policy:
        vdom: "{{ vdom }}"
        state: "present"
        firewall_dos_policy:
          policyid: 5  # Adjust policy ID as necessary
          name: "TCP_SYN_FLOOD"
          interface: "port1"  # Adjust interface as necessary
          srcaddr:
            - name: "any"
          dstaddr:
            - name: "INT_USERS address"  # Adjust destination address as necessary
          service:
            - name: "ALL_TCP"
          status: "enable"
          anomaly:
            - name: "tcp_syn_flood"
              threshold: 2000
              action: "pass"  # Change action to monitor
              log: "enable"
