---
- name: Send notify to Telegram
  hosts: localhost
  tasks:
    - name: Notify via Telegram
      community.general.telegram:
        token: '7281232336:AAEOPDNXGU2iwOwyo3C8yVFV4a5tAdvNGIQ'
        api_method: sendMessage
        api_args:
          chat_id: 7397749412  # Replace with your actual chat ID
          text: "Hello! AnsiBot here, I will be the one alerting you in the event of any cyber attack on the T931 lab!"
          parse_mode: markdown
          disable_web_page_preview: true
          disable_notification: true
