---
- name: Send dynamic security alert messages to PCs
  hosts: Monitoring
  gather_facts: no
  tasks:
    - name: Display dynamic security alert based on attack type
      community.windows.win_msg:
        display_seconds: 30
        msg: "Security Alert: {{ attacker_ip }} is suspected of a {{ attack_type }}. Immediate action required."

- hosts: fortigate
  gather_facts: no
  collections:
    - fortinet.fortios
  connection: httpapi
  vars:
    vdom: "root"
    ansible_httpapi_use_ssl: no
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 80
  tasks:
    - name: Define the malicious IP address
      fortios_firewall_address:
        vdom: "{{ vdom }}"
        state: "present"
        firewall_address:
          name: "Malicious_IP"
          subnet: "{{ attacker_ip }} 255.255.255.255"

    # Block traffic from port1 to port2
    - name: Block traffic from port1 to port2
      fortios_firewall_policy:
        vdom: "{{ vdom }}"
        state: "present"
        firewall_policy:
          policyid: 51
          name: "Block_port1_to_port2"
          srcintf: [{"name": "port1"}]
          dstintf: [{"name": "port2"}]
          srcaddr: [{"name": "Malicious_IP"}]
          dstaddr: [{"name": "any"}]
          action: "deny"
          schedule: "always"
          service: [{"name": "ALL"}]
          logtraffic: "all"